FROM golang:latest

WORKDIR /app

ENV GO111MODULE=on

COPY etc/ indexes/ pkg/ utils/ /app/
COPY go.mod go.sum main.go /app/

RUN go mod download

#COPY . .

RUN go build -o elktools .

# Set variables and config

ENTRYPOINT ["./elktools"]